spring:
  application:
    name: user-server
  config:
    import: optional:file:.env[.properties]

  cloud:
    kubernetes:
      discovery:
        enabled: ${K8S_DISCOVERY_ENABLED:false}

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=${Auth_DB_SCHEMA}&stringtype=unspecified
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: ${Auth_DB_SCHEMA}

  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration-ms: ${JWT_ACCESSTOKEN_EXPIRATION_MS:1000000}
    refresh-token-expiration-ms: ${JWT_REFRESHTOKEN_EXPIRATION_MS:1209600000}

  data:
    redis:
      host: localhost
      port: 6379
      database: 310

eureka:
  client:
    enabled: ${EUREKA_ENABLED:false}
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

